require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PrevisaosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Previsao. As you add validations to Previsao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrevisaosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all previsaos as @previsaos" do
      previsao = Previsao.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:previsaos)).to eq([previsao])
    end
  end

  describe "GET #show" do
    it "assigns the requested previsao as @previsao" do
      previsao = Previsao.create! valid_attributes
      get :show, {:id => previsao.to_param}, valid_session
      expect(assigns(:previsao)).to eq(previsao)
    end
  end

  describe "GET #new" do
    it "assigns a new previsao as @previsao" do
      get :new, {}, valid_session
      expect(assigns(:previsao)).to be_a_new(Previsao)
    end
  end

  describe "GET #edit" do
    it "assigns the requested previsao as @previsao" do
      previsao = Previsao.create! valid_attributes
      get :edit, {:id => previsao.to_param}, valid_session
      expect(assigns(:previsao)).to eq(previsao)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Previsao" do
        expect {
          post :create, {:previsao => valid_attributes}, valid_session
        }.to change(Previsao, :count).by(1)
      end

      it "assigns a newly created previsao as @previsao" do
        post :create, {:previsao => valid_attributes}, valid_session
        expect(assigns(:previsao)).to be_a(Previsao)
        expect(assigns(:previsao)).to be_persisted
      end

      it "redirects to the created previsao" do
        post :create, {:previsao => valid_attributes}, valid_session
        expect(response).to redirect_to(Previsao.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved previsao as @previsao" do
        post :create, {:previsao => invalid_attributes}, valid_session
        expect(assigns(:previsao)).to be_a_new(Previsao)
      end

      it "re-renders the 'new' template" do
        post :create, {:previsao => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested previsao" do
        previsao = Previsao.create! valid_attributes
        put :update, {:id => previsao.to_param, :previsao => new_attributes}, valid_session
        previsao.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested previsao as @previsao" do
        previsao = Previsao.create! valid_attributes
        put :update, {:id => previsao.to_param, :previsao => valid_attributes}, valid_session
        expect(assigns(:previsao)).to eq(previsao)
      end

      it "redirects to the previsao" do
        previsao = Previsao.create! valid_attributes
        put :update, {:id => previsao.to_param, :previsao => valid_attributes}, valid_session
        expect(response).to redirect_to(previsao)
      end
    end

    context "with invalid params" do
      it "assigns the previsao as @previsao" do
        previsao = Previsao.create! valid_attributes
        put :update, {:id => previsao.to_param, :previsao => invalid_attributes}, valid_session
        expect(assigns(:previsao)).to eq(previsao)
      end

      it "re-renders the 'edit' template" do
        previsao = Previsao.create! valid_attributes
        put :update, {:id => previsao.to_param, :previsao => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested previsao" do
      previsao = Previsao.create! valid_attributes
      expect {
        delete :destroy, {:id => previsao.to_param}, valid_session
      }.to change(Previsao, :count).by(-1)
    end

    it "redirects to the previsaos list" do
      previsao = Previsao.create! valid_attributes
      delete :destroy, {:id => previsao.to_param}, valid_session
      expect(response).to redirect_to(previsaos_url)
    end
  end

end
